language: java

# For some reason Oracle JDK didn't install correctly on xenial or bionic
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9

jobs:
  include:
    # Use Ubuntu Bionic for the more recent Java versions (OpenJDK)
    - stage: Test
      jdk: openjdk10
      dist: bionic
    - jdk: openjdk11
      dist: bionic
    - jdk: openjdk12
      dist: bionic
    - jdk: openjdk13
      dist: bionic

    - stage: Test Coverage
      jdk: oraclejdk8
      after_success: mvn clean test jacoco:report coveralls:report
    - stage: Deploy Artifacts
      if: tag IS present
      jdk: oraclejdk8
      before_install:
        - openssl aes-256-cbc -K $encrypted_6678f8a25f19_key -iv $encrypted_6678f8a25f19_iv -in .travis/singingbushgpgkey.asc.enc -out .travis/singingbushgpgkey.asc -d
        - gpg2 --fast-import .travis/singingbushgpgkey.asc
      script: mvn deploy -B --settings=.travis/settings.xml -DskipTests=true
      on:
        tags: true
  # allow_failures:
  #   - jdk: openjdk13
