language: java

dist: trusty

jobs:
  include:
    - stage: Build using various JDK versions
        jdk:
          - oraclejdk6
          - oraclejdk7
          - oraclejdk8
          - oraclejdk9
          - openjdk7
    - stage: Test Coverage
        jdk: oraclejdk8
        after_success: mvn clean test jacoco:report coveralls:report
