language: java

dist: trusty

jobs:
  include:
    - stage: Build using various JDK versions
      jdk: oraclejdk8
    - jdk: oraclejdk9
    - jdk: openjdk8
    - stage: Test Coverage
      jdk: oraclejdk8
      after_success: mvn clean test jacoco:report coveralls:report
    - stage: Deploy
      jdk: oraclejdk8
      script: mvn clean deploy
      on:
        branch: master
